# Generated by Django 5.0 on 2024-02-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_officeward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designation",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documenttype",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fiscalyear",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="judgecommittee",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="officeward",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
    ]
