# Generated by Django 5.0 on 2024-01-13 16:41

import django.db.models.deletion
import nepali_datetime_field.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("birth_date", nepali_datetime_field.models.NepaliDateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("others", "Others"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("mobile_number", models.CharField(max_length=15, unique=True)),
                ("citizenship_no", models.CharField(max_length=20)),
                ("citizenship_issue_district", models.CharField(max_length=200)),
                (
                    "citizenship_issue_date",
                    nepali_datetime_field.models.NepaliDateField(),
                ),
                ("grandfather_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PermanentAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("municipality", models.CharField(max_length=100)),
                ("ward", models.IntegerField()),
                (
                    "consumer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumer.consumer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("municipality", models.CharField(max_length=100)),
                ("ward", models.IntegerField()),
                (
                    "consumer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="consumer.consumer",
                    ),
                ),
            ],
        ),
    ]
