# Generated by Django 5.0 on 2024-01-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="gender",
            field=models.CharField(
                choices=[("male", "पुरुष"), ("female", "महिला"), ("others", "अन्य")],
                max_length=10,
            ),
        ),
    ]
