# Generated by Django 5.0 on 2024-01-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consumer", "0002_alter_consumer_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="birth_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="consumer",
            name="citizenship_issue_date",
            field=models.DateField(),
        ),
    ]
