# Generated by Django 5.0 on 2024-02-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0005_alter_casereportd_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereportd",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="casestage",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="casesubtype",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="casetype",
            name="status",
            field=models.CharField(
                choices=[("निष्क्रिय", "निष्क्रिय"), ("सक्रिय", "सक्रिय")],
                default="सक्रिय",
                max_length=20,
            ),
        ),
    ]
