# Generated by Django 5.0 on 2023-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("act_law", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actlaw",
            name="is_deleted",
            field=models.BooleanField(default=True),
        ),
    ]
