# Generated by Django 5.0 on 2023-12-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("act_law", "0002_actlaw_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actlaw",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
